CREATE TABLE IF NOT EXISTS TB_PERMISSAO (
	COD_PERMISSAO SERIAL,
	DESCRICAO VARCHAR(50),
	CONSTRAINT pk_permissao PRIMARY KEY(COD_PERMISSAO)
);

INSERT INTO TB_PERMISSAO (COD_PERMISSAO, DESCRICAO) VALUES (777666, 'ADMIN');
INSERT INTO TB_PERMISSAO (COD_PERMISSAO, DESCRICAO) VALUES (777667, 'ESTUDANTE');
INSERT INTO TB_PERMISSAO (COD_PERMISSAO, DESCRICAO) VALUES (777668, 'EMPRESA');