CREATE TABLE TB_CURSO(
    COD_CURSO SERIAL,
    DESCRICAO VARCHAR(50),
    TIPO_CURSO VARCHAR(50),
    IND_ATIVO BOOLEAN DEFAULT(TRUE),
    CONSTRAINT pk_curso PRIMARY KEY(COD_CURSO)
--     INCLUIDO_POR VARCHAR(50),
--     DATA_INCLUSAO DATETIME,
--     ALTERADO_POR VARCHAR(50),
--     DATA_ALTERACAO DATETIME
);