CREATE TABLE IF NOT EXISTS TB_PERMISSAO (
	COD_PERMISSAO SERIAL,
	DESCRICAO VARCHAR(50),
	DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
	CONSTRAINT pk_permissao PRIMARY KEY(COD_PERMISSAO)
);

INSERT INTO TB_PERMISSAO (COD_PERMISSAO, DESCRICAO, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777666, 'ADMIN', NOW(), NOW());
INSERT INTO TB_PERMISSAO (COD_PERMISSAO, DESCRICAO, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777667, 'ESTUDANTE', NOW(), NOW());
INSERT INTO TB_PERMISSAO (COD_PERMISSAO, DESCRICAO, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777668, 'EMPRESA', NOW(), NOW());
