CREATE TABLE TB_HIST_ESCOLAR(
    COD_HIST_ESCOLAR SERIAL,
    NVL_ESCOLARIDADE VARCHAR(50),
    INST_ENSINO VARCHAR(50),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR(50),
    IND_ATIVO BOOLEAN DEFAULT(TRUE),
    CURSO INT,
    ESTUDANTE INT,
    CONSTRAINT pk_hist_escolar PRIMARY KEY(COD_HIST_ESCOLAR),
    CONSTRAINT fk_hist_escolar_curso FOREIGN KEY(CURSO) REFERENCES TB_CURSO(COD_CURSO)
--     INCLUIDO_POR VARCHAR(50),
--     DATA_INCLUSAO DATETIME,
--     ALTERADO_POR VARCHAR(50),
--     DATA_ALTERACAO DATETIME
);