CREATE TABLE TB_HIST_ESCOLAR(
    COD_HIST_ESCOLAR SERIAL,
    NVL_ESCOLARIDADE VARCHAR(50),
    CURSO VARCHAR(50),
    INST_ENSINO VARCHAR(50),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR(50),
    IND_ATIVO BOOLEAN DEFAULT 'TRUE',
    COD_ESTUDANTE INT NOT NULL,
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
    CONSTRAINT pk_hist_escolar PRIMARY KEY(COD_HIST_ESCOLAR),
    CONSTRAINT fk_hist_escolar_est FOREIGN KEY(COD_ESTUDANTE) REFERENCES TB_ESTUDANTE(COD_ESTUDANTE)
);