CREATE TABLE TB_USU_PERM(
	COD_PERMISSAO INT,
	COD_USUARIO INT,
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
	CONSTRAINT pk_usu_perm PRIMARY KEY(COD_PERMISSAO, COD_USUARIO),
	CONSTRAINT fk_usu_perm_perm FOREIGN KEY(COD_PERMISSAO) REFERENCES TB_PERMISSAO(COD_PERMISSAO),
	CONSTRAINT fk_usu_perm_usu FOREIGN KEY(COD_USUARIO) REFERENCES TB_USUARIO(COD_USUARIO)
);
