CREATE TABLE TB_CONTATO(
    COD_CONTATO SERIAL,
    TIP_CONTATO VARCHAR(50),
    DESC_CONTATO VARCHAR(50),
    VALOR_CONTATO VARCHAR(50),
    CONSTRAINT pk_contato PRIMARY KEY(COD_CONTATO)
--     INCLUIDO_POR VARCHAR(50),
--     DATA_INCLUSAO DATETIME,
--     ALTERADO_POR VARCHAR(50),
--     DATA_ALTERACAO DATETIME
);