CREATE TABLE TB_CONTATO(
    COD_CONTATO SERIAL,
    TIP_CONTATO VARCHAR(50),
    DESC_CONTATO VARCHAR(50),
    VALOR_CONTATO VARCHAR(50),
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
    CONSTRAINT pk_contato PRIMARY KEY(COD_CONTATO)
);

INSERT INTO TB_CONTATO (COD_CONTATO, TIP_CONTATO, VALOR_CONTATO) VALUES (777666, 'TELEFONE', '1132345143');

-- CREATE OR REPLACE FUNCTION TRG_AUDITORIA() RETURNS TRIGGER AS $trg_audit$
--     BEGIN
--         IF (TG_OP = 'UPDATE') THEN
--             UPDATE COD_CONTATO SET DATA_ALTERACAO = NOW() WHERE COD_CONTATO = NEW.COD_CONTATO;
--         ELSIF (TG_OP = 'INSERT') THEN
--             UPDATE COD_CONTATO SET DATA_INCLUSAO = NOW() WHERE COD_CONTATO = NEW.COD_CONTATO;
--         END IF;
--         RETURN NULL; 
--     END;
-- $trg_audit$ LANGUAGE plpgsql;
-- 
-- CREATE TRIGGER trg_audit
-- AFTER INSERT OR UPDATE ON COD_CONTATO
--     FOR EACH ROW EXECUTE FUNCTION TRG_AUDITORIA();