CREATE TABLE TB_CONTATO(
    COD_CONTATO SERIAL,
    TIP_CONTATO VARCHAR(10),
    DESC_CONTATO VARCHAR(50),
    VALOR_CONTATO VARCHAR(50),
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
    CONSTRAINT pk_contato PRIMARY KEY(COD_CONTATO)
);

INSERT INTO TB_CONTATO (COD_CONTATO, TIP_CONTATO, VALOR_CONTATO, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777666, 'CEL', '1132345143', NOW(), NOW());
