CREATE TABLE TB_CONTATO(
    COD_CONTATO SERIAL,
    TIP_CONTATO VARCHAR(10),
    DESC_CONTATO VARCHAR(50),
    VALOR_CONTATO VARCHAR(100),
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
    CONSTRAINT pk_contato PRIMARY KEY(COD_CONTATO)
);