CREATE TABLE TB_ESTUD_VAGA(
    COD_ESTUDANTE VARCHAR(25),
    COD_VAGA INT,
    IND_ATIVO BOOLEAN DEFAULT(TRUE),
    STATUS VARCHAR(50),
-- 	INCLUIDO_POR VARCHAR(50),
-- 	DATA_INCLUSAO DATETIME,
-- 	ALTERADO_POR VARCHAR(50),
-- 	DATA_ALTERACAO DATETIME,
    CONSTRAINT pk_estud_vaga PRIMARY KEY(COD_ESTUDANTE, COD_VAGA),
    CONSTRAINT fk_estud_vaga_estud FOREIGN KEY(COD_ESTUDANTE) REFERENCES TB_ESTUDANTE(COD_ESTUDANTE),
    CONSTRAINT fk_estud_vaga_vaga FOREIGN KEY(COD_VAGA) REFERENCES TB_VAGA(COD_VAGA)
);