CREATE TABLE TB_EXP_PROFISSIONAL(
	COD_EXP_PROFISSIONAL SERIAL,
	COD_ESTUDANTE INT NOT NULL,
	COD_ENDERECO INT,
	NOME_EMPRESA VARCHAR(75),
	CARGO VARCHAR(30),
	DESCRICAO TEXT,
    DATA_INICIO DATE,
	DATA_FIM DATE,
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
	CONSTRAINT pk_exp_prof PRIMARY KEY(COD_EXP_PROFISSIONAL),
	CONSTRAINT fk_exp_prof_estd FOREIGN KEY(COD_ESTUDANTE) REFERENCES TB_ESTUDANTE(COD_ESTUDANTE),
	CONSTRAINT fk_exp_prof_ender FOREIGN KEY(COD_ENDERECO) REFERENCES TB_ENDERECO(COD_ENDERECO)
);
