CREATE TABLE IF NOT EXISTS TB_USUARIO (
	COD_USUARIO SERIAL,
	SENHA	VARCHAR(50),
	PAPEL	VARCHAR(25)	DEFAULT 'COMUM',
	EMAIL	VARCHAR(50) NOT NULL,
	AVATAR	VARCHAR(100),
	IND_ATIVO	BOOLEAN	DEFAULT 'TRUE',
	CONSTRAINT pk_usuario PRIMARY KEY(COD_USUARIO)
);

INSERT INTO TB_USUARIO (COD_USUARIO, EMAIL, AVATAR) VALUES (777666, 'wecodetrabalho@gmail.com', 'https://lh3.googleusercontent.com/a/AATXAJzVFer4LrcGoSWZfhS3yAdsPFnF14xgql7Z5W8x=s96-c');
INSERT INTO TB_USUARIO (COD_USUARIO, EMAIL) VALUES (777667, 'emailempresateste@gmail.com');
INSERT INTO TB_USUARIO (COD_USUARIO, EMAIL) VALUES (777668, 'emailempresateste2@gmail.com');
INSERT INTO TB_USUARIO (COD_USUARIO, EMAIL) VALUES (777669, 'emailempresateste3@gmail.com');