CREATE TABLE IF NOT EXISTS TB_ENDERECO (
    COD_ENDERECO SERIAL,
	LOGRADOURO	VARCHAR(50)	NOT NULL,
	NUMERO	SMALLINT,
	BAIRRO	VARCHAR(50)	NOT NULL,
	CIDADE	VARCHAR(50)	NOT NULL,
	ESTADO	CHAR(2)	NOT NULL,
	CEP	INT	NOT NULL,
	COMPLEMENTO	VARCHAR(50),
	PONTO_REFERENCIA VARCHAR(50),
	IND_ATIVO BOOLEAN DEFAULT 'TRUE',
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
	CONSTRAINT pk_endereco PRIMARY KEY(COD_ENDERECO)
);

INSERT INTO TB_ENDERECO (COD_ENDERECO, LOGRADOURO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777666, 'RUA DO TESTE', 123, 'FLORES', 'SÃO PAULO', 'SP', 064235689, NOW(), NOW());
INSERT INTO TB_ENDERECO (COD_ENDERECO, LOGRADOURO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777667, 'AVENIDA DO ESTADO', 546, 'PERDISES', 'BELO HORIZONTE', 'MG', 06458659, NOW(), NOW());
INSERT INTO TB_ENDERECO (COD_ENDERECO, LOGRADOURO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777668, 'PONTE CASA VERDE', 2, 'TUCURUVI', 'SALVADOR', 'BA', 12659768, NOW(), NOW());
INSERT INTO TB_ENDERECO (COD_ENDERECO, LOGRADOURO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777669, 'RUA NOVA PISTA', NULL, 'SANTA MARIA', 'RIO BRANCO', 'AC', 35679865, NOW(), NOW());
INSERT INTO TB_ENDERECO (COD_ENDERECO, LOGRADOURO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, DATA_INCLUSAO, DATA_ALTERACAO) VALUES (777670, 'RODOVIA ANCHIETA', NULL, 'SAÚDE', 'SÃO PAULO', 'SP', 06894659, NOW(), NOW());