CREATE TABLE IF NOT EXISTS TB_ESTUDANTE (
	COD_ESTUDANTE VARCHAR(25),
	COD_PESSOA	INT NOT NULL UNIQUE,
	INST_ENSINO	VARCHAR(128),
	NVL_ENSINO	CHAR(2),
	EXP_PROFISSIONAL	TEXT,	
	IND_ATIVO	BOOLEAN	DEFAULT 'TRUE',
	CONSTRAINT pk_estudante PRIMARY KEY(COD_ESTUDANTE),
	CONSTRAINT pk_estudante_pess FOREIGN KEY(COD_PESSOA) REFERENCES TB_PESSOA(COD_PESSOA) 
);

INSERT INTO TB_ESTUDANTE(COD_ESTUDANTE, COD_PESSOA, INST_ENSINO, NVL_ENSINO, EXP_PROFISSIONAL) VALUES ('104562908477701076641', 777666, 'INSTITUTO FEDERAL DE SÃO PAULO', 'ES', 'RECEPCIONISTA');