CREATE TABLE IF NOT EXISTS TB_ESTUDANTE (
	COD_ESTUDANTE VARCHAR(25),
	COD_PESSOA	INT NOT NULL UNIQUE,
	IND_ATIVO	BOOLEAN	DEFAULT 'TRUE',
-- 	INCLUIDO_POR VARCHAR(50),
-- 	DATA_INCLUSAO DATETIME,
-- 	ALTERADO_POR VARCHAR(50),
-- 	DATA_ALTERACAO DATETIME,
	CONSTRAINT pk_estudante PRIMARY KEY(COD_ESTUDANTE),
	CONSTRAINT pk_estudante_pess FOREIGN KEY(COD_PESSOA) REFERENCES TB_PESSOA(COD_PESSOA) 
);

-- INSERT INTO TB_ESTUDANTE(COD_ESTUDANTE, COD_PESSOA, INST_ENSINO, NVL_ENSINO, EXP_PROFISSIONAL) VALUES ('104562908477701076641', 777666, 'INSTITUTO FEDERAL DE SÃO PAULO', 'ES', 'RECEPCIONISTA');