CREATE TABLE TB_EMPRESA (
	COD_EMPRESA	SERIAL	PRIMARY KEY,
	RAZAO_SOCIAL	VARCHAR(50)	NOT NULL,
	NOME_FANTASIA	VARCHAR(50),
	CNPJ	VARCHAR(20)	NOT NULL UNIQUE,
	COD_ENDERECO	SERIAL	REFERENCES TB_ENDERECO(COD_ENDERECO) NOT NULL,
	IND_ATIVO	BOOLEAN	DEFAULT 'TRUE'
);

INSERT INTO TB_EMPRESA(RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, COD_ENDERECO) VALUES ('TESTE LTDA', 'TESTES SEGUROS LTDA', '23.064.687/0001-24', 1);