CREATE TABLE TB_VAGA (
	COD_VAGA	SERIAL	PRIMARY KEY,
	COD_EMPRESA	SERIAL	REFERENCES TB_EMPRESA(COD_EMPRESA) NOT NULL,
	DESCRICAO	TEXT,
	SALARIO	MONEY,
	TITULO	VARCHAR(30),
	IND_ATIVO	BOOLEAN	DEFAULT 'TRUE'
);

INSERT INTO TB_VAGA(COD_EMPRESA, DESCRICAO, SALARIO, TITULO) VALUES (1, 'Vaga disponível para atuar no desenvolvimento front-end do nosso sistema focado em vagas de estágio!', '3500.98', 'Desenvolvedor Front-End');