CREATE TABLE TB_COMP_ESTUD(
	COD_COMPETENCIA SERIAL,
	COD_ESTUDANTE SERIAL,
	IND_ATIVO BOOLEAN DEFAULT(TRUE),
	FOREIGN KEY(COD_COMPETENCIA) REFERENCES TB_COMPETENCIA(COD_COMPETENCIA),
	FOREIGN KEY(COD_ESTUDANTE) REFERENCES TB_ESTUDANTE(COD_ESTUDANTE)
);