CREATE TABLE TB_COMP_VAGA(
	COD_COMPETENCIA INT,
	COD_VAGA INT,
    DATA_INCLUSAO TIMESTAMP,
	DATA_ALTERACAO TIMESTAMP,
	CONSTRAINT pk_comp_vaga PRIMARY KEY(COD_COMPETENCIA, COD_VAGA),
	CONSTRAINT fk_comp_vaga_comp FOREIGN KEY(COD_COMPETENCIA) REFERENCES TB_COMPETENCIA(COD_COMPETENCIA),
	CONSTRAINT fk_comp_vaga_vaga FOREIGN KEY(COD_VAGA) REFERENCES TB_VAGA(COD_VAGA)
);

INSERT INTO TB_COMP_VAGA VALUES(1, 777666, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(2, 777666, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(6, 777667, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(5, 777667, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(10, 777668, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(4, 777668, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(8, 777669, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(9, 777669, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(22, 777670, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(20, 777670, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(14, 777671, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(13, 777671, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(12, 777671, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(9, 777672, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(8, 777673, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(7, 777673, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(6, 777674, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(14, 777674, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(23, 777675, NOW(), NOW());
INSERT INTO TB_COMP_VAGA VALUES(25, 777675, NOW(), NOW());