CREATE TABLE TB_COMP_VAGA(
	COD_COMPETENCIA INT,
	COD_VAGA INT,
	IND_ATIVO BOOLEAN DEFAULT(TRUE),
	CONSTRAINT fk_comp_vaga_comp FOREIGN KEY(COD_COMPETENCIA) REFERENCES TB_COMPETENCIA(COD_COMPETENCIA),
	CONSTRAINT fk_comp_vaga_vaga FOREIGN KEY(COD_VAGA) REFERENCES TB_VAGA(COD_VAGA)
);