name: Deploy to development environment

on:
  push:
    branches: [ develop ]
  pull_request:
    types:
      - opened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run check
        run: ./gradlew check
  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run build
        run: ./gradlew build

      - name: Send to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
